# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-15 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskStatus',
        ),
    ]
