# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-15 15:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0006_auto_20170825_1253'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0023_userinvite'),
        ('email_wrapper_lib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccountConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(default=b'', max_length=254, verbose_name='From name')),
                ('label', models.CharField(default=b'', max_length=254, verbose_name='Inbox label')),
                ('privacy', models.PositiveSmallIntegerField(choices=[(0, 'Complete message'), (1, 'Date and recipients'), (2, 'Not at all')], default=0, verbose_name='Privacy')),
                ('shared_with_everyone', models.BooleanField(default=False, verbose_name='Shared with everyone')),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='email_wrapper_lib.EmailAccount', verbose_name='Email account')),
                ('owners', models.ManyToManyField(related_name='imelo_owned_email_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Owned email accounts')),
                ('shared_with_teams', models.ManyToManyField(related_name='imelo_shared_email_accounts', to='users.Team', verbose_name='Shared with teams')),
                ('shared_with_users', models.ManyToManyField(related_name='imelo_shared_email_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Shared with users')),
                ('tenant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.Tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
