# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-24 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0009_auto_20171212_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='start',
            field=models.DateTimeField(db_index=True, verbose_name='Start'),
        ),
    ]
