API_VERSION_V2 = 'v2.0'
SUPPORTED_API_VERSIONS = [API_VERSION_V2]

# Default / Sytstem folders.
FOLDER_INBOX = 'Inbox'
FOLDER_DRAFTS = 'Drafts'
FOLDER_SENT_ITEMS = 'SentItems'
FOLDER_DELETED_ITEMS = 'DeletedItems'
FOLDER_ALL_ITEMS = 'AllItems'
SYSTEM_FOLDERS = [FOLDER_INBOX, FOLDER_DRAFTS, FOLDER_SENT_ITEMS, FOLDER_DELETED_ITEMS, FOLDER_ALL_ITEMS]

# Writeble properties.
WP_ATTACHMENT = 'Attachments'
WP_BCC_RECIPIENTS = 'BccRecipients'
WP_BODY = 'Body'
WP_CATEGORIES = 'Categories'
WP_CC_RECIPIENTS = 'CcRecipients'
WP_FROM = 'From'
WP_IMPORTANCE = 'Importance'
WP_INFERENCE_CLASSIFICATION = 'InferenceClassification'
WP_IS_DELEIVERY_RECEIPT_REQUESTED = 'IsDeliveryReceiptRequested'
WP_IS_READ = 'IsRead'
WP_IS_READ_RECEIPT_REQUESTED = 'IsReadReceiptRequested'
WP_MULTI_VALUE_EXTENTED_PROPERTIES = 'MultiValueExtendedProperties'
WP_SENDER = 'Sender'
WP_SINGLE_VALUE_EXTENTED_PROPERTIES = 'SingleValueExtendedProperties'
WP_SUBJECT = 'Subject'
WP_TO_RECIPIENTS = 'ToRecipients'
WP_CONTENT_TYPE = 'ContentType'
WP_IS_INLINE = 'IsInline'
WP_NAME = 'Name'
WP_ITEM = 'Item'
WP_SIZE = 'Size'
WP_IS_FOLDER = 'IsFolder'
WP_PERMISSION = 'Permission'
WP_PREVIEW_URL = 'PreviewUrl'
WP_PROVIDER_TYPE = 'ProviderType'
WP_SOURCE_URL = 'SourceUrl'
WP_THUMBNAL_URL = 'ThumbnailUrl'

WRITABLE_MESSAGE_PROPERTIES = [WP_ATTACHMENT, WP_BCC_RECIPIENTS, WP_BODY, WP_CATEGORIES, WP_CC_RECIPIENTS, WP_FROM,
                               WP_IMPORTANCE, WP_INFERENCE_CLASSIFICATION, WP_IS_DELEIVERY_RECEIPT_REQUESTED,
                               WP_IS_READ, WP_IS_READ_RECEIPT_REQUESTED, WP_MULTI_VALUE_EXTENTED_PROPERTIES, WP_SENDER,
                               WP_SINGLE_VALUE_EXTENTED_PROPERTIES, WP_SUBJECT, WP_TO_RECIPIENTS]
WRITABLE_FILE_PROPERTIES = [WP_CONTENT_TYPE, WP_IS_INLINE, WP_NAME]
WRITABLE_ITEM_PROPERTIES = [WP_CONTENT_TYPE, WP_ITEM, WP_IS_INLINE, WP_NAME, WP_SIZE]
WRITABLE_REFERENCE_PROPERTIES = [WP_CONTENT_TYPE, WP_IS_FOLDER, WP_IS_INLINE, WP_NAME, WP_PERMISSION, WP_PREVIEW_URL,
                                 WP_PROVIDER_TYPE, WP_SOURCE_URL, WP_THUMBNAL_URL]

# Focused inbox classifications.
INFERENCE_CLASSIFICATION_FOCUSED = 'focused'
INFERENCE_CLASSIFICATION_OTHER = 'other'
INFERENCE_CLASSIFICATION_OPTIONS = [INFERENCE_CLASSIFICATION_FOCUSED, INFERENCE_CLASSIFICATION_OTHER]

# Mailbox settings properties.
SETTING_ARCHIVE_FOLDER = 'ArchiveFolder'
SETTING_AUTOMATIC_REPLIES = 'AutomaticRepliesSetting'
SETTING_TIME_ZONE = 'TimeZone'
SETTING_LANGUAGE = 'Language'
SETTING_OPTIONS = [SETTING_ARCHIVE_FOLDER, SETTING_AUTOMATIC_REPLIES, SETTING_TIME_ZONE, SETTING_LANGUAGE]

MAX_BATCH_SIZE = 20
