PreCommit:
  EsLint:
    enabled: true
    on_warn: 'fail'
    include: 'frontend/app/**/*.js'

  ScssLint:
    enabled: true
    on_warn: 'fail'

  PythonFlake8:
    enabled: true
    on_warn: 'fail'
    flags: ['--max-line-length=119']
    exclude: ['**/migrations/**', 'lily/google/**', '**/__init__.py', 'taskmonitor/**']

  TrailingWhitespace:
    enabled: true
    on_warn: 'fail'
    exclude: ['**/vendor/**/**', '**/*.svg']

  TravisLint:
    enabled: true
    on_warn: 'fail'

  CustomScript:
    enabled: true
    description: "Check python yapf formatting"
    required_executable: './checks/git/yapf.sh'
