PreCommit:
  EsLint:
    enabled: true
    on_warn: 'fail'
    include: 'frontend/app/**/*.js'
    required_executable: './node_modules/.bin/eslint'
    command: ['./node_modules/.bin/eslint', 'src', '__tests__', '--ext', '.js']

  ScssLint:
    enabled: true
    on_warn: 'fail'

  PythonFlake8:
    enabled: true
    on_warn: 'fail'
    flags: ['--max-line-length=119']
    exclude: ['**/migrations/**', 'lily/google/**', '**/__init__.py', 'taskmonitor/**']

  TrailingWhitespace:
    enabled: true
    on_warn: 'fail'
    exclude: ['**/vendor/**/**', '**/*.svg']

  TravisLint:
    enabled: true
    on_warn: 'fail'
