#!/usr/bin/env bash
set -eo pipefail

# The post_compile hook is run by heroku-buildpack-python

indent() {
    RE="s/^/       /"
    [ $(uname) == "Darwin" ] && sed -l "$RE" || sed -u "$RE"
}

echo "-----> In post-compile hook"

export PATH=/app/gettext/bin:$PATH

MANAGE_FILE=$(find . -maxdepth 3 -type f -name 'manage.py' | head -1)
MANAGE_FILE=${MANAGE_FILE:2}

echo "-----> Compiling translation files"
python "$MANAGE_FILE" compilemessages 2>&1 | indent

echo "-----> Done post-compile hook"
echo ""
