from django.utils.translation import ugettext
from django_otp.plugins.otp_totp.models import TOTPDevice
from otp_yubikey.models import RemoteYubikeyDevice
from two_factor.models import PhoneDevice
from two_factor.templatetags.two_factor import device_action


def get_info_text_for_device(device):
    if isinstance(device, TOTPDevice):
        return ugettext('Tokens will be generated by your token generator.')
    elif isinstance(device, PhoneDevice):
        return device_action(device)
    elif isinstance(device, RemoteYubikeyDevice):
        return ugettext('Tokens will be generated by your YubiKey.')
