# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-29 12:22
from __future__ import unicode_literals

from django.db import migrations


def integer_to_charfield(apps, schema_editor):
    EmailOutboxMessage = apps.get_model('email', 'EmailOutboxMessage')
    for email_outbox_message in  EmailOutboxMessage.objects.all():
        email_outbox_message.original_attachment_ids_char = email_outbox_message.original_attachment_ids
        email_outbox_message.template_attachment_ids_char = email_outbox_message.template_attachment_ids
        email_outbox_message.save()

def charfield_to_integer(apps, schema_editor):
    EmailOutboxMessage = apps.get_model('email', 'EmailOutboxMessage')
    for email_outbox_message in  EmailOutboxMessage.objects.all():
        email_outbox_message.original_attachment_ids = email_outbox_message.original_attachment_ids_char
        email_outbox_message.template_attachment_ids = email_outbox_message.template_attachment_ids_char
        email_outbox_message.save()

class Migration(migrations.Migration):

    dependencies = [
        ('email', '0033_auto_20170919_1547'),
    ]

    operations = [
        migrations.RunPython(integer_to_charfield, charfield_to_integer)
    ]
