# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-15 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0036_auto_20170929_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='color',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
