# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0006_auto_20170825_1253'),
        ('email', '0037_emailaccount_color'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='templatevariable',
            unique_together=set([('tenant', 'name', 'is_public')]),
        ),
    ]
