# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-14 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0039_auto_20180321_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaccount',
            name='previous_privacy',
            field=models.IntegerField(choices=[(0, 'Group inbox'), (1, 'Public personal inbox'), (2, 'Personal inbox, with shared metadata'), (3, 'Private inbox')], null=True),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='privacy',
            field=models.IntegerField(choices=[(0, 'Group inbox'), (1, 'Public personal inbox'), (2, 'Personal inbox, with shared metadata'), (3, 'Private inbox')], default=1),
        ),
        migrations.AlterField(
            model_name='sharedemailconfig',
            name='privacy',
            field=models.IntegerField(choices=[(0, 'Group inbox'), (1, 'Public personal inbox'), (2, 'Personal inbox, with shared metadata'), (3, 'Private inbox')], default=0),
        ),
    ]
