# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-17 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0040_auto_20180514_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailmessage',
            old_name='is_draft_message',
            new_name='is_draft',
        ),
        migrations.RenameField(
            model_name='emailmessage',
            old_name='is_inbox_message',
            new_name='is_inbox',
        ),
        migrations.RenameField(
            model_name='emailmessage',
            old_name='is_sent_message',
            new_name='is_sent',
        ),
        migrations.RenameField(
            model_name='emailmessage',
            old_name='is_spam_message',
            new_name='is_spam',
        ),
        migrations.RenameField(
            model_name='emailmessage',
            old_name='is_starred_message',
            new_name='is_starred',
        ),
        migrations.RenameField(
            model_name='emailmessage',
            old_name='is_trashed_message',
            new_name='is_trashed',
        ),
    ]
