# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-02 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0040_auto_20180514_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='message_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Email message'), (1, 'Reply email message'), (2, 'Reply-all email message'), (3, 'Forward email message'), (4, 'Forward-multi email message')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='message_type_to_id',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
