# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 12:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0041_auto_20180802_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailoutboxmessage',
            name='original_attachment_ids',
            field=models.TextField(default=b'', validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
