# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-06 13:00
from __future__ import unicode_literals

from django.db import migrations
import lily.utils.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0042_auto_20180827_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaccount',
            name='created',
            field=lily.utils.models.fields.CreatedDateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='modified',
            field=lily.utils.models.fields.ModifiedDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='created',
            field=lily.utils.models.fields.CreatedDateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='modified',
            field=lily.utils.models.fields.ModifiedDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
