# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-12 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lily.utils.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0008_auto_20180822_1308'),
        ('email', '0043_auto_20180906_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', lily.utils.models.fields.CreatedDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', lily.utils.models.fields.ModifiedDateTimeField(auto_now=True, verbose_name='modified')),
                ('remote_id', models.CharField(max_length=255, verbose_name='Google draft id')),
                ('send', models.BooleanField(verbose_name='Sending')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='email.EmailAccount')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft_info', to='email.EmailMessage', verbose_name='Message resource')),
                ('tenant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.Tenant')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
    ]
