# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-10 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0044_rename_label_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='body_html_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='email.EmailBody'),
        ),
    ]
