# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-27 10:35
from __future__ import unicode_literals

from django.db import migrations
import lily.messaging.email.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0044_auto_20181106_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emaildraftattachment',
            name='content_type',
        ),
        migrations.AlterField(
            model_name='emaildraftattachment',
            name='attachment',
            field=lily.messaging.email.models.models.CustomFileField(max_length=255, upload_to=lily.messaging.email.models.models.get_draft_attachment_upload_path),
        ),
    ]
