# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-16 13:16
from __future__ import unicode_literals

from django.db import migrations


def replace_null_with_empty_strings(apps, schema_editor):
    Recipient = apps.get_model('email', 'Recipient')
    Recipient.objects.filter(name=None).update(name='')
    Recipient.objects.filter(email_address=None).update(email_address='')

    EmailOutboxMessage = apps.get_model('email', 'EmailOutboxMessage')
    EmailOutboxMessage.objects.filter(bcc=None).update(bcc='')
    EmailOutboxMessage.objects.filter(body=None).update(body='')
    EmailOutboxMessage.objects.filter(cc=None).update(cc='')
    EmailOutboxMessage.objects.filter(headers=None).update(headers='')
    EmailOutboxMessage.objects.filter(subject=None).update(subject='')
    EmailOutboxMessage.objects.filter(original_message_id=None).update(original_message_id='')


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('email', '0044_auto_20181106_1003'),
    ]

    operations = [
        migrations.RunPython(replace_null_with_empty_strings, do_nothing),
    ]
