# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-16 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0045_auto_20181116_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailoutboxmessage',
            name='bcc',
            field=models.TextField(blank=True, verbose_name='bcc'),
        ),
        migrations.AlterField(
            model_name='emailoutboxmessage',
            name='body',
            field=models.TextField(blank=True, verbose_name='html body'),
        ),
        migrations.AlterField(
            model_name='emailoutboxmessage',
            name='cc',
            field=models.TextField(blank=True, verbose_name='cc'),
        ),
        migrations.AlterField(
            model_name='emailoutboxmessage',
            name='headers',
            field=models.TextField(blank=True, verbose_name='email headers'),
        ),
        migrations.AlterField(
            model_name='emailoutboxmessage',
            name='original_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='emailoutboxmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=255, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='email_address',
            field=models.CharField(blank=True, db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='name',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
