# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-16 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0046_remove_emailmessage_body_html'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailmessage',
            old_name='body_html_fk',
            new_name='body_html',
        ),
    ]
