# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-17 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import lily.messaging.email.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0048_auto_20181017_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='body_html',
            field=models.FileField(blank=True, upload_to=lily.messaging.email.models.models.get_body_html_upload_path),
        ),
    ]
