# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-06 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0036_auto_20170419_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Account'),
        ),
    ]
