# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-22 13:03
from __future__ import unicode_literals

from django.db import migrations
import lily.utils.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0037_auto_20180206_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='created',
            field=lily.utils.models.fields.CreatedDateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='modified',
            field=lily.utils.models.fields.ModifiedDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
