# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 12:26
from __future__ import unicode_literals

from django.db import migrations


def replace_null_with_empty_strings(apps, schema_editor):
    Deal = apps.get_model('deals', 'Deal')
    Deal.objects.filter(imported_from=None).update(imported_from='')


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('deals', '0038_auto_20180822_1303'),
    ]

    operations = [
        migrations.RunPython(replace_null_with_empty_strings, do_nothing),
    ]
