# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0039_auto_20180927_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='imported_from',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
