# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 14:43
from __future__ import unicode_literals

from django.db import migrations


def replace_null_with_empty_strings(apps, schema_editor):
    SocialMedia = apps.get_model('socialmedia', 'SocialMedia')
    SocialMedia.objects.filter(other_name=None).update(other_name='')
    SocialMedia.objects.filter(profile_url=None).update(profile_url='')


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('socialmedia', '0002_auto_20160610_1624'),
    ]

    operations = [
        migrations.RunPython(replace_null_with_empty_strings, do_nothing),
    ]
