# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0003_auto_20180927_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='other_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='profile_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
