# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-21 15:49
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_auto_20170717_2005'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contact',
            managers=[
                ('elastic_objects', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
