# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-21 13:25
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations
import lily.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_userinvite'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='lilyuser',
            managers=[
                ('objects', lily.users.models.LilyUserManager()),
                ('all_objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
