# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-14 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20171221_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='registration_finished',
            field=models.BooleanField(default=False, verbose_name='User has finished the registration process'),
        ),
        migrations.AlterField(
            model_name='lilyuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='lilyuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='is staff'),
        ),
    ]
