# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-11 14:15
from __future__ import unicode_literals

from django.db import migrations


def set_registration_finished(apps, schema_editor):
    UserInfo = apps.get_model('users', 'UserInfo')

    UserInfo.objects.all().update(registration_finished=True)


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0025_auto_20180514_0939'),
    ]

    operations = [
        migrations.RunPython(set_registration_finished, do_nothing),
    ]
