# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 14:45
from __future__ import unicode_literals

from django.db import migrations


def replace_null_with_empty_strings(apps, schema_editor):
    PhoneNumber = apps.get_model('utils', 'PhoneNumber')
    PhoneNumber.objects.filter(other_type=None).update(other_type='')

    Webhook = apps.get_model('utils', 'Webhook')
    Webhook.objects.filter(name=None).update(name='')


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0020_auto_20180822_1308'),
    ]

    operations = [
        migrations.RunPython(replace_null_with_empty_strings, do_nothing),
    ]
