# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0021_auto_20180927_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='other_type',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
