# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 14:20
from __future__ import unicode_literals

from django.db import migrations


def replace_null_with_empty_strings(apps, schema_editor):
    DocumentEvent = apps.get_model('integrations', 'DocumentEvent')
    DocumentEvent.objects.filter(document_status=None).update(document_status='')


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('integrations', '0008_documentevent_set_to_today'),
    ]

    operations = [
        migrations.RunPython(replace_null_with_empty_strings, do_nothing),
    ]
