# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_auto_20180927_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentevent',
            name='document_status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
