# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-07 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lily.importer.models
import lily.utils.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0008_auto_20180822_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', lily.utils.models.fields.CreatedDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', lily.utils.models.fields.ModifiedDateTimeField(auto_now=True, verbose_name='modified')),
                ('csv', models.FileField(max_length=500, upload_to=lily.importer.models.get_csv_import_upload_path)),
                ('tenant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.Tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
